server:
  port: 7002
eureka:
  instance:
    hostname: com7002.eureka
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://com7001.eureka:7001/eureka/