server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka,http://localhost:7001/eureka

