server:
  port: 88
spring:
  application:
    name: cloud-hystrix-consumer88
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
feign:
  hystrix:
    enabled: true #开启feign对hystrix的支持
