server:
  port: 91

spring:
  application:
    name: cloud-stream-rabbit-consumer91
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 消息消费者的配置
          destination: studyExchange # 从该交换机上消费消息
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: defaultRabbit  # 设置要绑定的消息服务的具体设置
          group: consumer  #设置消费者所在组(可防止多消费者才生的重复消费)
          #分组除了可以解决重复消费之外，还可以解决消息丢失。因为如果一个消费组只有一个消费者，一旦这个消费者挂了。那么
          #可能有些数据就不会被消费。如果消费者组中具有多个消费者，至少消息还可以被其他消费者消费

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: send-91.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址









